#!/usr/bin/bash

username=$(whoami)

install_and_config_av(){
	sudo apt-get install clamav clamav-daemon
	sudo systemctl stop clamav-freshclam)
	sudo freshclam
	echo "if sudo freshclam worked for your system?(yes/no)"
	read fresponse
	if [ "$fresponse" == yes ];then
		echo "OK"
	elif [ "$fresponse" == no ];then
		echo $(sudo mkdir /var/lib/clamav)
		echo $(cp daily.cvd /var/lib/clamav/daily.cvd)
		echo $(sudo systemctl start clamav-freshclam)
	fi
}

install_and_config_rootkit_hunter(){
	echo $(cd /tmp)
	echo $(wget http://downloads.sourceforge.net/project/rkhunter/rkhunter/1.4.6/rkhunter-1.4.6.tar.gz)
	echo $(tar -xvf rkhunter-1.4.6.tar.gz)
	echo $(cd rkhunter-1.4.6)
	echo $(./installer.sh --install)
}



install_and_config_malware_detect(){
	echo $(cd /usr/local/src)
	echo $(wget http://www.rfxn.com/downloads/maldetect-current.tar.gz)
	echo $(cd malwaredetect-1.5)
	echo $(./install.sh)
	echo "quarantine_hits = "1" >> /usr/local/maldetect/conf.maldet"
}


psad(){
	sudo apt inastall psad
	echo "psad Install [ OK ]"
	}
